# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: hello@ivanmontoro.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.ivanmontoro.com"
twitter_username: imontoro
github_username: imontoro
facebook_username: ivan.montoro

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
