# Site settings
title: "Iván Montoro"
header-img: "img/home-bg.jpg"
email: "hello@ivanmontoro.com"
description: "Ideas en la nube"
baseurl: ""
url: "http://www.ivanmontoro.com"
twitter_username: imontoro
github_username: imontoro
facebook_username: ivan.montoro
linkedin_username: ivanmontoro

# Build settings
markdown: kramdown
highlighter: pygments
#permalink: pretty
permalink: date
paginate: 5
paginate_path: "/p/:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
